version: "3.8"
services:
  front:
    container_name: front
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "83:80"
    networks:
      - app
networks:
  app:
    driver: bridge